apiVersion: v1
description: CouchDB instance for Hyperledger Fabric 
name: couchdb
version: 1.0.5
appVersion: 0.4.14
keywords:
  - blockchain
  - hyperledger
  - fabric
  - couchdb
home: http://hyperledger-fabric.readthedocs.io
sources:
  - https://github.com/hyperledger/fabric
maintainers:
  - name: h04x
    email: mohammedr62@gmail.com